### ISSUE TITLE
Error running the raw code 

### ISSUE THREAD

**Issue by mdshopon** [Jallet/Deconvnet-keras#1]
I cloned the repository and tried to run the raw code without any modification. This error raised:
Using Theano backend.
usage: Deconvnet-keras.py [-h] [--layer_name LAYER_NAME] [--feature FEATURE]
                          [--mode {max,all}]
                          image
Deconvnet-keras.py: error: too few arguments

Any explanation ?

**Comment by jalused** [comment]
Hi, this means you need some command line parameter to run the code. You need an image to visualize the cnn feature. Try this: python Deconvnet-keras.py husky.jpg.
