### ISSUE TITLE
Throws error while trying to get bias parameter of a layer

### ISSUE THREAD

**Issue by grvm20** [Jallet/Deconvnet-keras#3]
Hi,
I am on Keras 2.0.2. This throws an error when I try to get the bias from the layer weights. layer.get_weights() returns a list with 1 element and bias tries to get the second element.

**Comment by jalused** [comment]
Hi, try Keras 1.1, or you can have a look at the document of [keras](keras.io) to figure out difference of  the "get_weights" function between Keras 1.1 and Keras 2.0.2. I believe it is the version of Keras that cause your error.
